image: archlinux
oauth: pages.sr.ht/PAGES:RW
packages:
  - gcc
  - make
  - hut
  - clang
  - texinfo
environment:
  site: o-lang.org
sources:
  - https://git.sr.ht/~johnnyrichard/olang
tasks:
  - format: |
      cd olang
      make format
  - build: |
      cd olang
      make
      make docs-dist
  - check: |
      cd olang
      make check
  - check-spec: |
      cd olang
      ./contrib/bin/run-ebnf <(find tests/olc/ -name '*.ol' | xargs -L1 grep -Ev '(^#|^$)' | cat) 1> /dev/null
  - docs-publish: |
      cd olang
      if [ "$BUILD_REASON" = "" ]
      then
        hut pages publish -d $site docs/site.tar.gz
      fi

