image: archlinux
oauth: pages.sr.ht/PAGES:RW
packages:
  - gcc
  - make
  - hut
  - clang
  - pandoc-cli
environment:
  site: o-lang.org
sources:
  - https://git.sr.ht/~johnnyrichard/olang
tasks:
  - format: |
      cd olang
      make format
  - build: |
      cd olang
      make
      make docs-dist
  - check: |
      cd olang
      make check
  - docs-publish: |
      cd olang
      if [ "$BUILD_REASON" = "" ]
      then
        hut pages publish -d $site docs/site.tar.gz
      fi

