image: archlinux
oauth: pages.sr.ht/PAGES:RW
packages:
  - gcc
  - make
  - hut
  - clang
  - python-sphinx
sources:
  - https://git.sr.ht/~johnnyrichard/olang
environment:
  site: johnnyrichard.srht.site
tasks:
  - lint: |
      cd olang
      make linter
  - build: |
      cd olang
      make
  - check: |
      cd olang
      make check
  - docs: |
      cd olang/docs
      make html
      cd _build/html
      tar -czvf ../docs.tar.gz .
      hut pages publish -d $site ../docs.tar.gz

